# 没这个root true就会跟monorepo根目录的eslint狠狠冲突，好用的standard-with-typescript不适用于.vue文件
root: true
env:
    browser: true
    es2021: true
    # 为了让配置文件可以使用nodejs提供的变量和commonjs语法
    node: true
extends:
    - eslint:recommended
    - '@vue/eslint-config-typescript/recommended'
    - plugin:vue/vue3-recommended
    - plugin:vue-scoped-css/vue3-recommended
    - plugin:prettier/recommended
ignorePatterns:
    - /dist/*
    - /node_modules/*
    - '*.d.ts'
overrides: []
parser: vue-eslint-parser
parserOptions:
    ecmaVersion: latest
    ecmaFeatures:
        jsx: true
    parser: '@typescript-eslint/parser'
    sourceType: module
plugins:
    - '@typescript-eslint'
    - prettier
    - vue
rules:
    prettier/prettier: error
