extends:
    - stylelint-config-html
    - stylelint-config-recess-order
    - stylelint-config-sass-guidelines
    - stylelint-config-standard
    - stylelint-config-standard-vue
    - stylelint-config-tailwindcss
rules:
    at-rule-no-unknown:
    scss/at-rule-no-unknown:
        - true
        - ignoreAtRules:
            - tailwind
            - value
            - layer
