extends:
    - stylelint-config-html
    - stylelint-config-recess-order
    - stylelint-config-standard-scss
    - stylelint-config-standard-vue
    - stylelint-config-prettier
rules:
    at-rule-no-unknown:
    scss/at-rule-no-unknown:
        - true
        - ignoreAtRules:
            - tailwind
            - value
            - layer
