env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:prettier/recommended
overrides: []
ignorePatterns:
  - '**/dist/**/*.js'
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
plugins:
  - prettier
rules:
  '@typescript-eslint/triple-slash-reference': off
  '@typescript-eslint/no-misused-promises':
    - error
    - checksVoidReturn: false
  prettier/prettier: error
