env:
    browser: true
    es2021: true
extends:
    - standard-with-typescript
    - plugin:prettier/recommended
overrides: []
ignorePatterns:
    - '**/dist/**/*.js'
parserOptions:
    project: ./tsconfig.json
plugins:
    - prettier
rules:
    '@typescript-eslint/triple-slash-reference': off
    prettier/prettier: error
